### ISSUE TITLE
Login Telegram widget

### ISSUE THREAD

**Issue by gevera** [416d72/sveltegram#1]
Hi there. Thanks for all your work integrating my favorite two tools. Any ways to implement a telegram login widget ?

I am planning to use Telegram in my Svelte app as auth provider. 
Best regards

**Comment by amr3k** [comment]
Hi, this is interesting idea, I didn't plan it from the beginning, but I have no problem with adding it.

Let me see what I can do.

Also all contributions are welcome. 

Thanks

**Comment by gevera** [comment]
Hey, thanks for the reply. I've done something similar to this https://github.com/vchaptsev/vue-telegram-login/tree/master/src  , however something is missing and I can't figure it out

**Comment by amr3k** [comment]
I messed around with it two days ago, and I have an issue defining a global function from a svelte component.

I tried using `window.onTelegramAuth = (user) => console.log(user);` but it didn't work after authenticating with Telegram, it gives me a `ReferenceError`.

**Comment by gevera** [comment]
> I messed around with it two days ago, and I have an issue defining a global function from a svelte component.
> 
> I tried using `window.onTelegramAuth = (user) => console.log(user);` but it didn't work after authenticating with Telegram, it gives me a `ReferenceError`.


Did you try 

<svelte:window on:loginSuccess={loginSuccess}></

???

Or maybe you could you share your code or working branch. Maybe i could come up with something

**Comment by amr3k** [comment]
I just pushed v1.0.0 release including support for login button.

Let me know what do you think :)

**Comment by gevera** [comment]
Works like a charm. You're the man! Thank you
